import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import TopHeader from "./components/TopHeader";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastContainer } from "react-toastify";
import { Toaster } from "react-hot-toast";
const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <ToastContainer /> */}
          <Toaster
            // position="top-right"
            // reverseOrder={false}
            // gutter={8}
            // containerClassName=""
            // containerStyle={{}}
            // toastOptions={{
            //   // Define default options
            //   className: "",
            //   duration: 3000,

            //   // Default options for specific types
            //   success: {
            //     duration: 3000,
            //   },
            // }}
          />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
